### ISSUE TITLE
Is there illustration for 'Play the Dragon' challenge in Round 1A?

### ISSUE THREAD

**Issue by targetnull** [kamyu104/GoogleCodeJam-2017#1]
Hi, kamyu104

It's a great repo, thanks for your sharing. I'm currently trying to practice on this year's Codejam, but I'm having a little trouble in following your code for [Play the Dragon](https://github.com/kamyu104/GoogleCodeJam-2017/blob/master/Round%201A/play-the-dragon.py) challenge in Round 1A.

I understand most of your code because I have already looked at the official analysis, but regarding the function `cure_turn_for_debuff`, there seems to be some complicated math analysis. More specifically, [in line 59 to line 61](https://github.com/kamyu104/GoogleCodeJam-2017/blob/master/Round%201A/play-the-dragon.py#L59-L61), there is `elif D*D + 4*a*a + 4*a*D - 8*cur_Hd*D >= 0:` and `int(ceil((2*Ak - D - (D*D + 4*a*a + 4*a*D - 8*cur_Hd*D) ** 0.5) / (2*D)) - 1)`, which look confusing to me. Would you please give me some clues about the deduction of these expressions? I know that `D*D + 4*a*a + 4*a*D` is equivalent to `(D + 2*a)^2`, but where do I get this? It seems to me that these formulas just come out of blue.

I'm not an expert in algorithm but I'm trying to improve, I'd really appreciate it if you would illustrate a little.

**Comment by kamyu104** [comment]
Add some comments on the solution. Besides, this problem is rather hard if you want to use math formula to solve it correctly. It is hard to explain them all in few words. I suggest that you can just use some simulation to solve it in C++ rather than Python.
