### ISSUE TITLE
Doubt in a solution

### ISSUE THREAD

**Issue by JatinRanka** [kamyu104/GoogleCodeJam-2017#3]
https://github.com/kamyu104/GoogleCodeJam-2017/blob/master/Round%201C/ample-syrup.py

In the above solution, why are you using heapq instead of a normal list?

list.append() and list.remove(min(list)) can be used instead of heappush and heappop.

**Comment by kamyu104** [comment]
list.append() and list.remove(min(list)) is **O(K)**, but heappush and heappop is only **O(logK)**.
