### ISSUE TITLE
A Run Error

### ISSUE THREAD

**Issue by liuhaoyan0323** [kamyu104/GoogleCodeJam-2017#4]
Hi kamyu104!

I am a Chinese student.I'm not good at python.

I used your code,but it runs error, what should I do?

[GoogleCodeJam-2017/Round 3/mountain_tour](https://github.com/kamyu104/GoogleCodeJam-2017/blob/master/Round%203/mountain_tour.py)

**Comment by liuhaoyan0323** [comment]
Can you provide C++ code?

**Comment by kamyu104** [comment]
* The code for the repository was written in Python 2 several years ago.
* It should run in Python 2, not Python 3.
* Since the contest website was shut down, I can no longer restore my C++ code.
* Additionally, this repository is no longer updated.
